[tools]
node = "20"

[tasks.install]
description = "Install dependencies"
run = "npm install"

[tasks.min]
description = "Build and minify JavaScript files"
run = "npm run build"

[tasks.build]
description = "Build the project for production"
run = ["npm install", "npm run build"]

[tasks.dev]
description = "Start development server"
run = "python3 -m http.server 8000"

[tasks.clean]
description = "Clean build artifacts"
run = "rm -f translator.bundle.js translator.min.js"